stages:
  - build
  - release


build:
  stage: build
  script:
    - cp /home/gitlab-runner/configs/.env ./
    - docker-compose build

release:
  stage: release
  script:
    - cp /home/gitlab-runner/configs/.env ./
    - docker-compose -f docker-compose.yml -f prod.certbot.yml up -d
    - docker-compose exec -T app python manage.py collectstatic --no-input

  only:
    - gitlab-ci.yml

