# Generated by Django 4.0.3 on 2022-05-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Есть', 'есть'), ('Нет', 'нет')], default='есть', max_length=20, verbose_name='наличие'),
        ),
    ]
