# Generated by Django 4.0.3 on 2022-05-20 19:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, default=django.utils.timezone.now, upload_to='menu_photo', verbose_name='Фото блюда'),
            preserve_default=False,
        ),
    ]
