# Generated by Django 4.0.3 on 2022-05-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(
                upload_to='menu_photo', verbose_name='Фото блюда'),
        ),
    ]
