# Generated by Django 4.0.2 on 2022-05-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_telegramuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='user_id',
            field=models.PositiveSmallIntegerField(
                unique=True, verbose_name='Telegram Id пользователя'),
        ),
    ]
