# Generated by Django 4.0.2 on 2022-05-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_telegramuser_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='phone_number',
            field=models.PositiveSmallIntegerField(verbose_name='Телефон'),
        ),
    ]
