# Generated by Django 4.0.2 on 2022-05-27 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_telegramuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='translit_category_name',
            field=models.CharField(
                blank=True, max_length=200,
                null=True, verbose_name='Категория'),
        ),
    ]
