# Generated by Django 4.0.2 on 2022-05-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_category_translit_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='translit_description',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Транслитератор Описание блюда'),
        ),
        migrations.AddField(
            model_name='product',
            name='translit_product_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Транслитератор Название блюда'),
        ),
    ]
