# Generated by Django 4.0.2 on 2022-05-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_product_translit_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_name_translation',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Перевод Категория'),
        ),
        migrations.AlterField(
            model_name='category',
            name='translit_category_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Транслит Категория'),
        ),
    ]
