# Generated by Django 4.0.3 on 2022-05-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_category_category_name_translation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='О Нас')),
                ('telephone_number', models.PositiveBigIntegerField(max_length=15, verbose_name='Телефон компании')),
            ],
        ),
    ]
