# Generated by Django 4.0.3 on 2022-05-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_category_category_name_translation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_translation',
            field=models.CharField(
                blank=True, max_length=3000, null=True,
                verbose_name='Перевод описание блюд'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_translation',
            field=models.CharField(
                blank=True, max_length=200, null=True,
                verbose_name='Перевод блюд'),
        ),
    ]
