# Generated by Django 4.0.3 on 2022-05-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_aboutus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='telephone_number',
            field=models.PositiveIntegerField(verbose_name='Телефон компании'),
        ),
    ]
