# Generated by Django 4.0.3 on 2022-06-01 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_product_description_translation_and_more'),
        ('product', '0013_tablereservation_order_basket_id_and_more'),
        ('product', '0014_alter_aboutus_telephone_number'),
    ]

    operations = [
    ]
