# Generated by Django 4.0.3 on 2022-06-06 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_merge_20220602_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='id',
        ),
        migrations.AddField(
            model_name='tablereservation',
            name='condition',
            field=models.CharField(choices=[('Подтвержден', 'Подтвержден'),
                                            ('Не подтвержден',
                                             'Не подтвержден')],
                                   default='Новый', max_length=20,
                                   verbose_name='Состояние'),
        ),
        migrations.AddField(
            model_name='tablereservation',
            name='status',
            field=models.CharField(
                choices=[('Подтвержден', 'Подтвержден'),
                         ('Не подтвержден', 'Не подтвержден')],
                default='Не подтвержден',
                max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='user_id',
            field=models.PositiveSmallIntegerField(
                primary_key=True, serialize=False, unique=True,
                verbose_name='Telegram Id пользователя'),
        ),
    ]
