# Generated by Django 4.0.3 on 2022-06-04 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_merge_20220601_2131'),
        ('product', '0015_merge_20220602_1344'),
    ]

    operations = [
    ]
