# Generated by Django 4.0.3 on 2022-06-08 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_remove_telegramuser_id_tablereservation_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='telegram_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baskets_user', to='product.telegramuser', verbose_name='Телеграмм клиент'),
        ),
    ]
