# Generated by Django 4.0.3 on 2022-06-08 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_baskettoorder_shoppingcartorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcartorder',
            name='basket_id',
        ),
        migrations.CreateModel(
            name='ShoppingCartOrderBasketToOrder',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID')),
                ('baske_to_order', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='basket_to_orders',
                    to='product.baskettoorder', verbose_name='Id корзины')),
                ('shopping_cart_order', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='shopping_cart_orders',
                    to='product.shoppingcartorder', verbose_name='Id заказа')),
            ],
        ),
    ]
