# Generated by Django 4.0.3 on 2022-06-09 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_merge_20220604_2134'),
        ('product', '0019_remove_shoppingcartorder_basket_id_and_more'),
    ]

    operations = [
    ]
