# Generated by Django 4.0.3 on 2022-06-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product',
         '0021_statusshoppingcartorder_delete_merchanttelegramuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantTelegramUser',
            fields=[
                ('user_id', models.PositiveSmallIntegerField(
                    primary_key=True, serialize=False, unique=True,
                    verbose_name='Telegram Id пользователя')),
                ('first_name', models.CharField(
                    blank=True, max_length=100, null=True,
                    verbose_name='Имя')),
                ('last_name', models.CharField(
                    blank=True, max_length=100, null=True,
                    verbose_name='Фамилия')),
                ('phone_number', models.PositiveSmallIntegerField(
                    verbose_name='Телефон')),
                ('vcard', models.CharField(
                    blank=True, max_length=300, null=True,
                    verbose_name='Электронная карта')),
            ],
        ),
        migrations.RemoveField(
            model_name='baskettoorder',
            name='order',
        ),
        migrations.AlterField(
            model_name='shoppingcartorder',
            name='status',
            field=models.CharField(
                choices=[('Новый', 'Новый'), ('В процессе', 'В процессе'),
                         ('Выполнено', 'Выполнено')], default='Новый',
                max_length=20, verbose_name='Статус'),
        ),
        migrations.DeleteModel(
            name='StatusShoppingCartOrder',
        ),
    ]
