# Generated by Django 4.0.3 on 2022-06-15 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_merge_20220609_2139'),
        ('product', '0025_alter_shoppingcartorder_status'),
    ]

    operations = [
    ]
