# Generated by Django 4.0.3 on 2022-06-17 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_merge_20220615_1355'),
        ('product', '0026_merge_20220615_1421'),
    ]

    operations = [
    ]
