# Generated by Django 4.0.3 on 2022-06-17 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_merge_20220616_1914'),
        ('product', '0027_merge_20220617_1445'),
    ]

    operations = [
    ]
