# Generated by Django 4.0.3 on 2022-06-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_merge_20220617_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablereservation',
            name='condition',
        ),
        migrations.AlterField(
            model_name='tablereservation',
            name='status',
            field=models.CharField(
                choices=[('Новый', 'Новый'), ('В процессе', 'В процессе'),
                         ('Выполнено', 'Выполнено')], default='Новый',
                max_length=20, verbose_name='Статус'),
        ),
    ]
