# Generated by Django 4.0.3 on 2022-06-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_remove_tablereservation_date_n_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablereservation',
            name='date',
            field=models.DateField(verbose_name='Дата бронирования'),
        ),
        migrations.AlterField(
            model_name='tablereservation',
            name='time',
            field=models.TimeField(verbose_name='Время бронирования'),
        ),
    ]
