# Generated by Django 4.0.3 on 2022-06-22 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_alter_tablereservation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFeedback',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID')),
                ('quiz_answer', models.PositiveSmallIntegerField(
                    verbose_name='Оценка клиента')),
                ('description', models.CharField(
                    blank=True, max_length=5000, null=True,
                    verbose_name='Отзыв клиента')),
                ('telegram_user_id', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='telegram_users_client',
                    to='product.telegramuser',
                    verbose_name='Telegram Id пользователя')),
            ],
        ),
    ]
