# Generated by Django 4.0.3 on 2022-06-23 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_alter_tablereservation_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablereservation',
            name='phone_number',
        ),
    ]
