# Generated by Django 4.0.3 on 2022-06-23 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_customerfeedback'),
        ('product', '0036_remove_tablereservation_phone_number'),
    ]

    operations = [
    ]
