# Generated by Django 4.0.3 on 2022-06-23 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0037_merge_20220623_1121'),
        ('product', '0037_merge_20220623_1153'),
    ]

    operations = [
    ]
