# Generated by Django 4.0.3 on 2022-06-24 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0038_merge_20220623_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablereservation',
            name='telegram_user_id',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='table_user', to='product.telegramuser',
                verbose_name='Телеграмм клиент'),
        ),
    ]
