# Generated by Django 4.0.3 on 2022-06-24 04:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0038_merge_20220623_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID')),
                ('text', models.TextField(
                    max_length=3000, verbose_name='Текст отзыва')),
                ('created_at', models.DateTimeField(
                    auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(
                    auto_now=True, verbose_name='Время изменения')),
            ],
        ),
        migrations.AddField(
            model_name='customerfeedback',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now,
                verbose_name='Время создания'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.AddField(
            model_name='comment',
            name='feedback',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='feedback', to='product.customerfeedback',
                verbose_name='Обратная связь'),
        ),
    ]
