# Generated by Django 4.0.3 on 2022-06-24 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0040_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
