# Generated by Django 4.0.3 on 2022-06-27 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0042_alter_tablereservation_table_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablereservation',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2022-06-02 08:55:20.064000', verbose_name='Время создания'),
        ),
    ]
