# Generated by Django 4.0.3 on 2022-06-27 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0045_alter_tablereservation_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablereservation',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, verbose_name='Время создания'),
        ),
    ]
