# Generated by Django 4.0.3 on 2022-06-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0048_alter_tablereservation_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablereservation',
            name='updated_at',
            field=models.DateTimeField(
                auto_now=True, verbose_name='Время изменения'),
        ),
    ]
