# Generated by Django 4.0.3 on 2022-06-27 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0041_delete_comment'),
        ('product', '0049_tablereservation_updated_at'),
    ]

    operations = [
    ]
