# Generated by Django 4.0.3 on 2022-06-28 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0050_merge_20220627_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchanttelegramuser',
            name='auth_user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='auth_user_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
