# Generated by Django 4.0.3 on 2022-06-29 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0050_merge_20220627_1839'),
        ('product', '0052_comments_author'),
    ]

    operations = [
    ]
