# Generated by Django 4.0.3 on 2022-07-11 06:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('product', '0054_alter_shoppingcartorder_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchanttelegramuser',
            name='phone_number',
            field=models.BigIntegerField(verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='merchanttelegramuser',
            name='user_id',
            field=models.BigIntegerField(
                primary_key=True, serialize=False, unique=True,
                verbose_name='Telegram Id пользователя'
            ),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.BigIntegerField(verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='order',
            name='telegram_user_id',
            field=models.BigIntegerField(
                verbose_name='Telegram Id пользователя'
            ),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='phone_number',
            field=models.BigIntegerField(verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='user_id',
            field=models.BigIntegerField(
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name='Telegram Id пользователя'
            ),
        ),
    ]
