# Generated by Django 4.0.3 on 2022-07-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0055_alter_merchanttelegramuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merchanttelegramuser',
            options={'verbose_name': 'Мерчант', 'verbose_name_plural': 'Мерчант'},
        ),
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='telephone_number',
            field=models.BigIntegerField(verbose_name='Телефон компании'),
        ),
    ]
