# Generated by Django 4.0.3 on 2022-03-19 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='user_pics', verbose_name='Аватар')),
                ('about_profile', models.TextField(blank=True, max_length=1000, null=True, verbose_name='О себе')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='KZ', unique=True, verbose_name='Номер телефона')),
                ('gender', models.CharField(blank=True, choices=[('they', 'Не задано'), ('woman', 'Женщина'), ('man', 'Мужчина')], max_length=20, null=True, verbose_name='Пол')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
