# Generated by Django 4.0.3 on 2022-05-29 23:52

import api_client.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('email_verification_code', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('profile_filled', models.BooleanField(default=False)),
                ('kyc_verification_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_verified', models.BooleanField(default=False)),
                ('phone_verification_code', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name_cyrillic', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name_cyrillic', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name_latin', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name_latin', models.CharField(blank=True, max_length=255, null=True)),
                ('patronymic', models.CharField(blank=True, max_length=255, null=True)),
                ('iin_number', models.CharField(blank=True, max_length=12, null=True)),
                ('country_of_residence', models.CharField(blank=True, max_length=255, null=True)),
                ('city_of_residence', models.CharField(blank=True, max_length=255, null=True)),
                ('postcode', models.CharField(blank=True, max_length=255, null=True)),
                ('address_of_residence', models.CharField(blank=True, max_length=255, null=True)),
                ('citizenship_country', models.CharField(blank=True, max_length=255, null=True)),
                ('verification_document', models.CharField(blank=True, max_length=255, null=True)),
                ('verification_document_number', models.CharField(blank=True, max_length=255, null=True)),
                ('verification_document_expires_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', api_client.models.UserManager()),
            ],
        ),
    ]
